language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
  
matrix:
  allow_failures:
    - php: 7.4snapshot

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-interaction
